version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade --force-reinstall ./sagemaker-mlopsincome-p-wgnjxlqlug3k-modelbuild "awscli>1.20.30"

  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - |
        run-pipeline --module-name pipelines.income.pipeline \
          --role-arn "$SAGEMAKER_PIPELINE_ROLE_ARN" \
          --tags "[]" \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${ARTIFACT_BUCKET}\",\"pipeline_name\":\"census-income-pipeline\",\"model_package_group_name\":\"census-income-model-group\",\"base_job_prefix\":\"census-income\",\"input_data\":\"s3://${ARTIFACT_BUCKET}/income.txt\"}"
      - echo "SageMaker Pipeline created successfully."